name: Hello World
on: [push]
jobs:
  Test-Job:
    runs-on: ubuntu-latest
    container: python:3.10.4-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install flake8
          pip install requirements.txt
      - name: Linting
        run: python -m flake8

