name: Code Quality Verification
on: [push, pull-request]
jobs:
  Linting:
    runs-on: ubuntu-latest
    container:
      image: python:3.10.4-bullseye
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements_dev.txt
      - name: Run linting
        run: python -m flake8 ./src
  
  Unit-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.4]
    container:
      image: python:${{ matrix.python-version }}-bullseye
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements_dev.txt
      - name: Run unit tests
        run: python -m pytest --cov=src --cov-fail-under=28 tests

